apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nvfoymri
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/go-nvfoymri:4e5ee4b4c35b4df3ee3681585d88c7f3de3726a4@sha256:f780559052f7e1f1d6c8afc78418a5837c4622bc393d495fd29dcb0beef48333
          name: container-image
